stages:
  download-data:
    cmd: kaggle competitions download -c house-prices-advanced-regression-techniques
  unzip-data:
    cmd: 'with zipfile.ZipFile .\house-prices-advanced-regression-techniques.zip r
      as zip_ref:'
